[workspace]
members = [ "api-utils","blog_os-device","blog_os-device-api", "blog_os-log", "blog_os-pci", "blog_os-syscalls","blog_os_vfs", "blog_os_vfs_api", "kdriver-api", "kernel-utils"]
resolver = "3"
