[package]
name = "blog_std"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"
blog_os-syscalls = {path = "../../kernel-libs/blog_os-syscalls"}
talc = "4.4.3"
lock_api = "0.4.14"


[lib]
test = false
bench = false
